const coinNames = {
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  BNB: 'Binance Coin',
  USDT: 'Tether',
  USDC: 'USD Coin',
  XRP: 'Ripple',
  DOGE: 'Dogecoin',
  ADA: 'Cardano',
  SOL: 'Solana',
  TRX: 'TRON',
  DOT: 'Polkadot',
  LTC: 'Litecoin',
  SHIB: 'Shiba Inu',
  AVAX: 'Avalanche',
  MATIC: 'Polygon',
  APT: 'Aptos',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  SUI: 'Sui',
  PEPE: 'Pepe Coin',
  TON: 'Toncoin',
  FIL: 'Filecoin',
  INJ: 'Injective',
  NEAR: 'Near Protocol',
  XLM: 'Stellar',
  ATOM: 'Cosmos',
  ALGO: 'Algorand',
  VET: 'VeChain',
  EGLD: 'MultiversX',
  FTM: 'Fantom',
  HBAR: 'Hedera',
  MKR: 'Maker',
  AAVE: 'Aave',
  RUNE: 'THORChain',
  LDO: 'Lido DAO',
  SAND: 'The Sandbox',
  MANA: 'Decentraland',
  GALA: 'Gala',
  FLOW: 'Flow',
  CHZ: 'Chiliz',
  XTZ: 'Tezos',
  THETA: 'Theta Network',
  ZIL: 'Zilliqa',
  DASH: 'Dash',
  COMP: 'Compound',
  CRV: 'Curve DAO',
  ENS: 'Ethereum Name Service'
};

module.exports = coinNames;
